[package]
name = "tasky"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["cargo"] }
csv = "1.3.0"
inquire = "0.7.5"
uuid = { version = "1.9.1", features = ["v4"] }
